# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgisfabricupdate
                                 A QGIS plugin
 QGIS PLugin to update the BDC Fabric
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-12
        copyright            : (C) 2023 by ecoLink Fiber (https://www.ecolink.coop)
        email                : noc@ecolink.coop
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qgisfabricupdate class from file qgisfabricupdate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgisfabricupdate import qgisfabricupdate
    return qgisfabricupdate(iface)
