---
#- name: Update repositories cache and install "slapd" package
#  apt:
#    name: slapd
#    update_cache: yes

- name: Generate ldap content
  template: src=templates/example.net.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/frr/bgpd.conf

