name: my_app
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  x509csr: ^1.0.0
  asn1lib: ^0.5.15
  pointycastle: 1.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
