---
- name: write the Quagga daemons settings
  template: src=templates/daemons dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/frr/daemons

- name: write the FRR bgpd config file
  template: src=templates/bgpd.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/frr/bgpd.conf

- name: write the FRR zebra settings
  template: src=templates/zebra.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/frr/zebra.conf

