---

- name: Include interfaces.d to the main interface config file
  template: src=templates/interfaces.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/network/interfaces owner=root group=root mode=0644
  #notify: reload networking

- name: configure the interfaces / bonds / brides / SVIs ...
  template: src=templates/interfaces_config.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/network/interfaces.d/interfaces
  #notify: reload networking

