---

- name: Set spare interfaces file
  template: src=templates/interfaces.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/network/interfaces owner=root group=root mode=0644

- name: Set fabric loopback(s)
  template: src=templates/lo_config.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/network/interfaces.d/lo owner=root group=root mode=0644

- name: Configure all ethernet intefaces as fabric links
  template: src=templates/interfaces_config.j2 dest=/var/lib/lxc/{{ ansible_host }}/rootfs/etc/network/interfaces.d/eth{{ item }}
  with_items: "{{ interfaces }}"

