---
- name: Create and start containers
  lxc_container:
    name: "{{ item.name }}"
    container_log: true
    state: started
    template: debian
    template_options: --release jessie
    # NOTE: This container_command below is copied from
    # https://lists.linuxcontainers.org/pipermail/lxc-users/2014-February/006304.html
    #container_command: |
    #  [ -f /etc/systemd/system/sigpwr.target ] || ln -s /usr/lib/systemd/system/halt.target /etc/systemd/system/sigpwr.target
  with_items:
    "{{ containers }}"

#- name: Enable autostart containers
#  lineinfile: dest=/var/lib/lxc/{{ item.name }}/config line="lxc.start.auto = 1" state=present
#  with_items:
#    "{{ containers }}"
